# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  fileSystems."/mnt/files" =
    { device = "nas.staudacher.dev:/files";
      fsType = "nfs";
      options = [ "x-systemd.automount" "noauto" "x-systemd.mount-timeout=10s" "timeo=15" "soft" ];
    };

  fileSystems."/mnt/media" =
    { device = "nas.staudacher.dev:/media";
      fsType = "nfs";
      options = [ "x-systemd.automount" "noauto" "x-systemd.mount-timeout=10s" "timeo=15" "soft" ];
    };

  fileSystems."/mnt/backup" =
    { device = "nas.staudacher.dev:/backup";
      fsType = "nfs";
      options = [ "x-systemd.automount" "noauto" "x-systemd.mount-timeout=10s" "timeo=15" "soft" ];
    };

  fileSystems."/mnt/seedbox" =
    { device = "nas.staudacher.dev:/seedbox";
      fsType = "nfs";
      options = [ "x-systemd.automount" "noauto" "x-systemd.mount-timeout=10s" "timeo=15" "soft" ];
    };
}
