# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [
    "cryptd"
    "evdi"
    "i915"
  ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  hardware.firmware = [ pkgs.linux-firmware ];

  boot.initrd.luks.devices."luksfs".device = "/dev/disk/by-partlabel/luks";
  boot.initrd.systemd.enable = true;
  boot.initrd.systemd.tpm2.enable = true;

  boot.kernelParams = [
    # Fixes the "Atomic update failure" and flickering/lag (Thunderbolt dock)
    "i915.enable_psr=0"
    # Ensures the new Meteor Lake Xe graphics architecture uses the right firmware
    "i915.enable_guc=3"
    # Optional: helps with bandwidth management on some Dell docks
    "intel_iommu=on"
  ];

  # Ensure you have the latest firmware for Meteor Lake
  hardware.firmware = [ pkgs.linux-firmware ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXOS";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "discard=async"
      "subvol=@"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/EFI";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-label/NIXOS";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "discard=async"
      "subvol=@home"
    ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-label/NIXOS";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "discard=async"
      "subvol=@log"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-label/NIXOS";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "discard=async"
      "subvol=@nix"
    ];
  };

  fileSystems."/var/lib/swap" = {
    device = "/dev/disk/by-label/NIXOS";
    fsType = "btrfs";
    options = [
      "nodatacow"
      "subvol=@swap"
    ];
  };

  swapDevices = [
    {
      device = "/var/lib/swap/swapfile";
      size = 32 * 1024; # 32 GB
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
