# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/621f9ef6-579e-49b8-aaa6-675760b41095";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" "ssd" "discard=async" "subvol=@" ];
    };

  boot.initrd.luks.devices."luksfs".device = "/dev/disk/by-uuid/3ae49f77-1c79-4725-9c1a-13e49748df83";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/32EE-2ADA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/621f9ef6-579e-49b8-aaa6-675760b41095";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" "ssd" "discard=async" "subvol=@home" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/621f9ef6-579e-49b8-aaa6-675760b41095";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" "ssd" "discard=async" "subvol=@log" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/621f9ef6-579e-49b8-aaa6-675760b41095";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" "ssd" "discard=async" "subvol=@nix" ];
    };

  fileSystems."/var/lib/swap" =
    { device = "/dev/disk/by-uuid/621f9ef6-579e-49b8-aaa6-675760b41095";
      fsType = "btrfs";
      options = [ "nodatacow" "subvol=@swap" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s13f0u3u4i5.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp114s0f0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
